<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | CashappAgent (Rank Math SEO)</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #334155;
						background-color: #0f172a;
						margin: 0;
						padding: 30px 20px;
					}
					.container {
						max-width: 1080px;
						margin: 0 auto;
						background: #1e293b;
						border: 1px solid #334155;
						border-radius: 16px;
						padding: 32px;
						box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 8px 10px -6px rgba(0, 0, 0, 0.5);
					}
					.header {
						border-bottom: 1px solid #334155;
						padding-bottom: 24px;
						margin-bottom: 24px;
					}
					.badge {
						display: inline-block;
						background: rgba(0, 214, 50, 0.15);
						color: #00D632;
						border: 1px solid rgba(0, 214, 50, 0.3);
						font-size: 11px;
						font-weight: 700;
						text-transform: uppercase;
						letter-spacing: 0.05em;
						padding: 4px 10px;
						border-radius: 9999px;
						margin-bottom: 12px;
					}
					h1 {
						color: #ffffff;
						font-size: 26px;
						margin: 0 0 10px 0;
						font-weight: 800;
						letter-spacing: -0.02em;
					}
					.description {
						color: #94a3b8;
						font-size: 14px;
						line-height: 1.6;
						margin: 0;
					}
					.description a {
						color: #00D632;
						text-decoration: none;
					}
					.description a:hover {
						text-decoration: underline;
					}
					.nav-bar {
						display: flex;
						gap: 12px;
						flex-wrap: wrap;
						margin-top: 16px;
					}
					.nav-link {
						background: #0f172a;
						border: 1px solid #334155;
						color: #cbd5e1;
						padding: 6px 14px;
						border-radius: 8px;
						font-size: 12px;
						font-weight: 600;
						text-decoration: none;
						transition: all 0.2s;
					}
					.nav-link:hover {
						background: #00D632;
						color: #000000;
						border-color: #00D632;
					}
					.stats {
						display: flex;
						align-items: center;
						justify-content: space-between;
						background: #0f172a;
						border: 1px solid #334155;
						border-radius: 10px;
						padding: 12px 18px;
						margin-bottom: 20px;
						font-size: 13px;
						color: #94a3b8;
					}
					.stats strong {
						color: #ffffff;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						font-size: 13px;
						text-align: left;
					}
					th {
						background-color: #0f172a;
						color: #94a3b8;
						font-weight: 600;
						padding: 12px 16px;
						border-bottom: 1px solid #334155;
						text-transform: uppercase;
						font-size: 11px;
						letter-spacing: 0.05em;
					}
					td {
						padding: 14px 16px;
						border-bottom: 1px solid #334155;
						color: #cbd5e1;
						word-break: break-all;
					}
					tr:hover td {
						background-color: rgba(255, 255, 255, 0.03);
					}
					td a {
						color: #38bdf8;
						text-decoration: none;
						font-weight: 500;
					}
					td a:hover {
						color: #00D632;
						text-decoration: underline;
					}
					.footer {
						margin-top: 24px;
						padding-top: 16px;
						border-top: 1px solid #334155;
						font-size: 12px;
						color: #64748b;
						display: flex;
						justify-content: space-between;
						align-items: center;
						flex-wrap: wrap;
						gap: 10px;
					}
					.pill {
						background: rgba(56, 189, 248, 0.1);
						color: #38bdf8;
						border: 1px solid rgba(56, 189, 248, 0.2);
						padding: 2px 8px;
						border-radius: 6px;
						font-size: 11px;
						font-weight: 600;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<div class="header">
						<span class="badge">Rank Math SEO XML Sitemap</span>
						<h1>CashappAgent Sitemap Index</h1>
						<p class="description">
							Generated by <strong>Rank Math SEO</strong> format. This is an XML Sitemap intended for indexing by search engines such as Google, Bing, DuckDuckGo, and Yandex.
						</p>
						<div class="nav-bar">
							<a href="/sitemap_index.xml" class="nav-link">Sitemap Index</a>
							<a href="/page-sitemap.xml" class="nav-link">Page Sitemap</a>
							<a href="/product-sitemap.xml" class="nav-link">Product Sitemap</a>
							<a href="/post-sitemap.xml" class="nav-link">Post Sitemap</a>
							<a href="/category-sitemap.xml" class="nav-link">Category Sitemap</a>
							<a href="/" class="nav-link">&#8592; Back to Website</a>
						</div>
					</div>

					<xsl:choose>
						<!-- Case 1: Sitemap Index -->
						<xsl:when test="sitemap:sitemapindex">
							<div class="stats">
								<span>This XML Sitemap Index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap)"/></strong> sub-sitemaps.</span>
								<span>Primary Index: <strong>sitemap_index.xml</strong></span>
							</div>
							<table>
								<thead>
									<tr>
										<th width="70%">Sitemap URL</th>
										<th width="30%">Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:sitemapindex/sitemap">
										<tr>
											<td>
												<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
											</td>
											<td>
												<xsl:value-of select="sitemap:lastmod"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:when>

						<!-- Case 2: URL Set (Page / Product / Post Sitemap) -->
						<xsl:when test="sitemap:urlset">
							<div class="stats">
								<span>This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</span>
								<span>Format: <strong>Sitemaps.org 0.9 + Image Schema</strong></span>
							</div>
							<table>
								<thead>
									<tr>
										<th width="45%">URL Address</th>
										<th width="10%">Images</th>
										<th width="15%">Change Frequency</th>
										<th width="10%">Priority</th>
										<th width="20%">Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:urlset/sitemap:url">
										<tr>
											<td>
												<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
											</td>
											<td>
												<xsl:choose>
													<xsl:when test="image:image">
														<span class="pill"><xsl:value-of select="count(image:image)"/> Images</span>
													</xsl:when>
													<xsl:otherwise>
														<span style="color:#64748b;">0</span>
													</xsl:otherwise>
												</xsl:choose>
											</td>
											<td>
												<xsl:value-of select="sitemap:changefreq"/>
											</td>
											<td>
												<xsl:value-of select="sitemap:priority"/>
											</td>
											<td>
												<xsl:value-of select="sitemap:lastmod"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:when>
					</xsl:choose>

					<div class="footer">
						<span>Domain: <strong>https://cashappagent.com</strong></span>
						<span>Compliant with Google Search Console, Bing Webmaster &amp; Rank Math SEO standard</span>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
